- README.md
- package.json
- src/index.js
- test/src/index.spec.js
This one's a bit longer than just the EventBridge integration because I pulled the docker ip parsing out of the port forwarding section to avoid duplicate code.
> feat(services): Detect and enable fsevent forwarding

- README.md
- src/args.js
- src/index.js
- src/output.js
- src/utils.js
- test/fixtures/docker-ps.js
- test/src/args.spec.js
- test/src/output.spec.js
- test/src/utils.spec.js
This PR includes the following:
* Closes #35; will warn if (potentially) orphaned services/containers are found at runtime
* Adds `devlab --cleanup` to `stop` and `rm` any Devlab services
* Adds `devlab --cleanup-all` to `stop` and `rm` ALL containers
> feat(utils): adds orphan identification and cleanup utils

- README.md
The current link 404s since paths are case sensitive.
> docs(readme): fix license link

- src/utils.js
> fix(utils): fix cli name typo `devlab` -> `lab`

- README.md
- package.json
- src/command.js
- src/index.js
- src/services.js
- src/tempdir.js
- test/fixtures/instance.js
- test/setup.js
- test/src/command.spec.js
- test/src/tempdir.spec.js
Instead of creating local `devlab.sh` this will create in the OS's temp dir, mount, and execute.
Why this wasn't done initially is on me; I just defaulted to `/tmp` but this caused issues on Mac and Circle. Now the temp directory is determined by the `/src/tempdir` module which will allow either a custom setting via the `DEVLAB_TMP` environment variable, or will try to determine the best temp directory to use.
Tested both on my linux server and on my local Mac.
Closes #49 by no longer storing this exec script local.
> fix(exec-script-tmp): uses tmp and mounts volume instead of creating locally

- src/config.js
- test/fixtures/devlab-syntax-error.yml
- test/src/config.spec.js
Currently, the same message is used when there is no devlab.yml as when there is an invalid one.  Also, YML errors are not shown making it tough to know what is wrong.
This PR specifies the exact issue with config, either missing or invalid.  An invalid config will now also show the location and nature of the syntax error.
**Missing**
```
› lab test
✖ Cannot load config file. Please ensure you have a valid ./devlab.yml file or specify one with the `-c` flag
```
**Invalid**
```
› lab test
✖ Cannot load config file. Please ensure you have a valid ./devlab.yml file or specify one with the `-c` flag
```
**Missing**
```
› lab test
✖ Please create a ./devlab.yml file or specify one with the `-c` flag.
```
**Invalid**
```
› lab test
✖ Please fix the errors in devlab.yml:
can not read a block …
```
> feat(config): better config error messages

- src/index.js
- src/services.js
Closes #41 
Instead of dumping logs this stops the process with an indication of what services failed so they can be investigated by inspecting docker logs.
> feat(service-start-errors): outputs names of failed services

- README.md
- circle.yml
- package.json
- src/args.js
- src/index.js
- src/utils.js
- test/fixtures/docker-ps.js
- test/src/args.spec.js
- test/src/index.spec.js
- test/src/utils.spec.js
As shown in #54, `--cleanup` with 20 stray containers took 1m 42s.  This is because they were shut down in series.
This PR adds async parallel support to actions, allowing us to kick off a process for every container simultaneously.  The result, shutting down any number of containers only takes as long as the longest container.  Woot!  🦉
> feat(utils): handle async actions

- README.md
- src/index.js
- src/services.js
- test/fixtures/instance.js
- test/fixtures/service.js
- test/project/devlab.yml
- test/src/services.spec.js
Allows users to specify `stopTimeSecs` property on service containers which will call `docker stop -t <n.Integer>' with custom timeout. Defaults to Docker default of `10s`.
Closes #58
> feat(stop-grace-period): handles stopTimeSecs prop on service containers

- README.md
- src/services.js
- test/project/devlab.yml
- test/src/services.spec.js
Can now set `stopTimeSecs` per service or globally (in the root of `devlab.yml` config). The system will prioritize 1) service settings, 2) global settings then 3) default to `10`.
> feat(global-stop-time): adds ability to set stopTimeSecs globally

- package.json
- src/command.js
- src/proc.js
- src/services.js
- src/utils.js
- test/project/.eslintrc
- test/src/args.spec.js
- test/src/command.spec.js
- test/src/index.spec.js
- test/src/proc.spec.js
- test/src/services.spec.js
- test/system/run.js
- test/system/tests.json
1. Remove `eslint` (not used) and update `standard`
1. Normalize array bracket spacing.  The project used a mix of `[foo]` and `[ foo ]`.  I went with the most common, no spaces: `[foo]`.
1. Add [`snazzy`](https://github.com/feross/snazzy)
**Before:**
**After:**
> chore(lint): update lint and normalize style

- README.md
- src/command.js
This is a bit of a hack. Pushing out a patch so our CI builds don't fail because of old Docker version on Circle.
> fix(devlab-no-rm): return DEVLAB_NO_RM env var support for CI

- README.md
- src/args.js
- src/services.js
- test/project/devlab.yml
- test/src/args.spec.js
- test/src/services.spec.js
- test/system/tests.json
This PR introduces support for disabling services via the command line, either individually with`-d <service>`, or collectively with `--disable-all`.
Disabling services for chained tasks still functions the same as it currently does—ie., if a task in the chain requires one of the disabled services, it will start as normal.
> Feat: disable services via command line argument

- README.md
No ticket. PR just removes outdated section, as service removal is now handled internally based on Docker version.
> docs(README): cut outdated service removal section

- src/utils.js
- test/src/utils.spec.js
Closes #78.
Now instead of being comma separated, orphaned containers are separated by new lines like:
```
⚠ These containers may not have exited correctly:
- bc_elasticsearch_B1tRKhcEW
- bc_ftp_B1tRKhcEW
⚠ You can attempt to remove these by running `binci --cleanup`
```
And the `cleanup` output lists the container names instead of their ids:
```
Stopping 6 containers:
✔ bc_elasticmq_SJ5Q9354-
✔ bc_aws-dynamodb_SJ5Q9354-
✔ bc_mysql_SJ5Q9354-
✔ bc_postgres_SJ5Q9354-
✔ bc_elasticsearch_SJ5Q9354-
✔ bc_ftp_SJ5Q9354-
```
> refactor(cleanup): match format in orphan warning and cleanup

- src/command.js
- test/src/command.spec.js
Currently, if an environment variable is not set, binci will convert it to the string literal `null` before passing it into the container. This can cause issues with the default shell behavior, since it would be expected to be an empty string (and therefore falsey) but instead the `null` string literal causes it to be treated as truthy. Example:
```
env:
- FOO=${UNSET_ENV_VAR}
```
```sh
echo ${FOO:-defaultValue} # null
```
```
env:
- FOO=${UNSET_ENV_VAR}
```
```sh
echo ${FOO:-defaultValue} # defaultValue
```
> feat(env): do not convert undefined environment values to the string "null"

- README.md
Neither Kent nor I can get `pkg` to compile this thing anymore, and the old binary locations aren't accessible anymore. Let's remove the option to avoid confusion until we solve it.
> docs(README): Remove binaries

- src/command.js
- test/fixtures/instance.js
- test/src/command.spec.js
- test/src/services.spec.js
A TTY is not provided on some CI test runners (notably, AWS CodeBuild), and results in Binci failing to run with the message `the input device is not a TTY`. This change only connects the TTY if stdout itself is a TTY.
(Note: still testing this change)
> fix(command): Do not run with -it if not on a TTY

- src/command.js
- src/images.js
Hi,
I've fixed a bug that causes binci to fail when using a custom Dockerfile while working in a project directory that contains upper case characters. Docker, in fact, doesn't allow upper case characters in the images name.
I've called the "toLowerCase()" function in order to "sanitize" images name when necessary.
Tests apart I haven't checked if there are other corner cases like that though.
> [FIX] Docker image generation fails if project directory has uppercase characters

- src/images.js
- src/index.js
- test/src/images.spec.js
- test/src/index.spec.js
More for consideration than anything, since this is pretty simplistic and doesn't exactly _fix_ #87 (and definitely not #99). Instead of intercepting and parsing Docker's output at runtime, this just preemptively checks if there are missing images, and prints a courtesy message letting the user know which will be pulled as part of start-up (implying some delay, which is what led to originally opening that issue).
> Print missing local images before service start

- src/command.js
- src/dewindowize.js
- src/index.js
This fix will address issues #105 and #106 . 
The problem is that Docker expect Windows paths in the following format:
`/C/path/to/directory`
Here's an example error when we use the plain process.cwd() method:
```
PS C:\GitHub\node-openid-provider> binci test
√ Starting services vault, db
√ Running Task
‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧
docker: Error response from daemon: the working directory 'C:\GitHub\node-openid-provider' is invalid, it needs to be an absolute path.
See 'docker run --help'.
‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧
× Command failed
PS C:\GitHub\node-openid-provider>
```
The exact same issue applies to the tmpdir that is used to mount docker volumes. This fix still requires the use of BINCI_TMP env variable that's set to an absolute Windows path.
> Fix issue with Windows path being rejected by Docker for Windows

- README.md
- src/command.js
- test/fixtures/binci.yml
- test/fixtures/instance.js
- test/src/services.spec.js
So once upon a time two days ago I started using DynamoDB Local in my test stack. Amazon, in its endless campaign to make shit difficult, doesn't support customizing DDB local via env vars, only cli options. Which, in a docker container, means passing your own command string.
No big deal, I thought. Surely Kent and I thought of this already. Lemmie just check the Binci docs.
...nope, turns out we have zero way to tell services to use a different command for startup!
Now we do :). And suddenly DDB local works for me!
> feat(services): Add command property
